# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- next-major-release

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'

- task: DotNetCoreCLI@2
  displayName: DotNetCore build
  inputs:
    command: 'build'
    projects: '*.csproj'

- task: Npm@1
  displayName: npm install azure functions core tools
  inputs:
    command: 'custom'
    customCommand: 'install -g azure-functions-core-tools --unsafe-perm true'

- task: Npm@1
  displayName: npm install
  inputs:
    command: 'install'

- task: CmdLine@2
  displayName: func extensions install
  inputs:
    script: 'func extensions install'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Npm@1
  displayName: npm run build
  inputs:
    command: 'custom'
    customCommand: 'run build --production'

- task: ArchiveFiles@2
  displayName: Archive files
  inputs:
    rootFolderOrFile: '$(build.sourcesdirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/output.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: Publish build artefacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/output.zip' 
    artifactName: 'drop'